name = "CausalGraphInterface"
uuid = "b41ab49a-79bc-5eac-acbb-517b17bd5c16"
version = "0.1.0-DEV"
authors = ["Bjarke Hautop Kristensen <bjarke.hautop@gmail.com>"]

[workspace]
projects = ["test", "docs"]

[deps]
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"

[extensions]
MakieExt = "Makie"
NetworkLayoutExt = "NetworkLayout"

[compat]
Makie = "0.24.11"
NetworkLayout = "0.4.10"
Preferences = "1.5.2"
Random = "1.11.0"
Statistics = "1.11.1"
julia = "1.10"
