module CausalGraphInterface

include("core.jl")

export CausalEdge,
    CausalGraph,
    DAG,
    UG,
    PDAG,
    ADMG,
    UNKNOWN,
    adjacency,
    topological_sort,
    ancestors,
    descendants,
    exogenous_nodes,
    markov_blanket,
    anteriors,
    posteriors,
    skeleton,
    moralize,
    subgraph,
    directed,
    neighbors,
    parents,
    children,
    spouses,
    districts,
    has_edge,
    undirected,
    bidirected,
    partially_directed,
    partially_undirected,
    partial,
    node,
    caugi,
    is_dag,
    is_pdag,
    is_ug,
    is_admg,
    is_caugi,
    nodes,
    is_simple,
    is_acyclic,
    generate_graph,
    simulate_data
end
